### ISSUE TITLE
File upload fails on using Multipart File Upload in HDIV 2.1.9

### ISSUE THREAD

**Issue by dhinesherode91** [hdiv/hdiv#74]
I am using HDIV 2.1.9 in my application containing Struts 1.3.8 and Spring 3.2.
HDIV works fine in all modules except in Multipart file upload.

Initially while working on struts multipart upload forms, I got the following error when my page renders.

'HTTP Status 500 - In order to enable HDIV multipart processing, MultipartResolver must be of org.hdiv.web.multipart.HdivCommonsMultipartResolver or org.hdiv.web.multipart.HdivStandardServletMultipartResolver type'.

I was using 'org.springframework.web.multipart.commons.CommonsMultipartResolver' previously and when I chaged that to 
'org.hdiv.web.multipart.HdivCommonsMultipartResolver', the page rendered properly without any issues.

But When I browse any of the file and click Upload button, the upload is not successful and always throws the validation message
'Please select a file to upload'.

On Debugging I could find that in my Struts Action, the request contains the file object which is always null.

Am I missing any Multipart configuration or anything else here ?

Below is the  log trace once I click the Upload button.

"10 Apr 2015 12:08:26 DEBUG org.hdiv.web.multipart.HdivCommonsMultipartResolver - Found multipart file [formFile1] of size 11574 bytes with original filename
[yyyyyyyyyyy.jpg], stored at [D:\tomcat-blue\tomcat_7\7.0.42\work\Catalina\localhost\xxxxx\upload_c0091696_2af2_422b_8d8e_b119ab2dc039_00000014.tmp]
10 Apr 2015 12:08:26 DEBUG org.hdiv.util.HDIVUtil - Stripping jsessionid from url /xxxxx/element/uploadFiles.do
10 Apr 2015 12:08:26 DEBUG org.hdiv.session.SessionHDIV - Getting page with id:25
10 Apr 2015 12:08:26 DEBUG org.hdiv.session.SessionHDIV - Getting page with id:25
10 Apr 2015 12:08:26 DEBUG org.hdiv.session.StateCache - Page with [28] added to the cache.
10 Apr 2015 12:08:26 DEBUG org.hdiv.session.SessionHDIV - Added new page with id:28
10 Apr 2015 12:08:26 DEBUG org.hdiv.session.SessionHDIV - Added new page with id:28
10 Apr 2015 12:08:26 DEBUG org.hdiv.web.multipart.HdivCommonsMultipartResolver - Cleaning up multipart file [formFile1] with original filename [celebrations.
jpg], stored at [D:\tomcat-blue\tomcat_7\7.0.42\work\Catalina\localhost\xxxxx\upload_c0091696_2af2_422b_8d8e_b119ab2dc039_00000014.tmp]
10 Apr 2015 12:08:26 DEBUG org.hdiv.filter.RequestWrapper - New RequestWrapper instance.
10 Apr 2015 12:08:26 DEBUG org.hdiv.filter.ResponseWrapper - New ResponseWrapper instance."

Please share your thoughts.

Thanks in Advance.

**Comment by gillarramendi** [comment]
It looks like `hdiv-spring-mvc` is loaded instead of `hdiv-struts-1`.
Do you have `hdiv-spring-mvc.jar` file in your classpath? Remove it and it will work!

**Comment by dhinesherode91** [comment]
Thanks for the response.

But by doing so, I am getting 'NoClassDefFoundError' for 'org/hdiv/web/servlet/support/HdivRequestDataValueProcessor' during server start up.
I hope the above mentioned class will be in hdiv-spring-mvc library.

Please find the stack trace below.

org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [hdiv-config.xml]; nested
exception is java.lang.NoClassDefFoundError: org/hdiv/web/servlet/support/HdivRequestDataValueProcessor
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:413)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:539)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:451)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
        at com.schawkds.common.web.util.spring.init.SafeContextLoaderListener.contextInitialized(SafeContextLoaderListener.java:71)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1653)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/hdiv/web/servlet/support/HdivRequestDataValueProcessor
        at org.hdiv.config.xml.ConfigBeanDefinitionParser.createRequestDataValueProcessor(ConfigBeanDefinitionParser.java:466)
        at org.hdiv.config.xml.ConfigBeanDefinitionParser.parse(ConfigBeanDefinitionParser.java:222)
        at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:73)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1432)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1422)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:187)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:147)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:101)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:495)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
        ... 27 more
Caused by: java.lang.ClassNotFoundException: org.hdiv.web.servlet.support.HdivRequestDataValueProcessor
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1714)
        at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1559)

**Comment by gillarramendi** [comment]
Ok, this issue is fixed on master and it will not happen in HDIV 2.1.10 we are going to release just today ;-)

**Comment by dhinesherode91** [comment]
Thanks.
I will try the latest and let you know the status :)

**Comment by dhinesherode91** [comment]
Hi,

I have updated my HDIV to 2.1.10 and when I tried to start my tomcat server, the server is not getting started. It just hangs up and doesn't throw any error or exception.

Is anyother configuartion related changes introduced in 2.1.10 ?
Because when I am using 2.1.9 the server gets started and application is deployed properly .

Please share your thoughts.

Thanks.

**Comment by gillarramendi** [comment]
The configuration is the same.
Set the log in debug level, maybe you can see more info there.

**Comment by dhinesherode91** [comment]
Thanks for the info. I got some minor issue in my local while upgrading to 2.1.10 and have fixed it now.

But the file upload issue is still occuring in 2.1.10.
My application has upload screens in both Spring and struts pages.
One thing I have noted here is, In spring screen the file upload is occuring properly and there is no issue.
But When I upload from struts screen, the file object on reaching struts action is NULL.

For your Info,
Regarding the multipart configuration, I have introduced the following code in my application context xml replacing the spring commons multipart resolver.

'<bean id="multipartResolver" class="org.hdiv.web.multipart.HdivCommonsMultipartResolver">
		<property name="maxUploadSize" value="100000" />
	</bean>'

Is there any other multipart changes I have to make in struts-config.xml or anywhere else to make the file upload to be work on struts screen?

Thanks in Advance.

**Comment by dhinesherode91** [comment]
the xml code missed out in above post,
'bean id="multipartResolver" class="org.hdiv.web.multipart.HdivCommonsMultipartResolver"
    property name="maxUploadSize" value="100000" 
bean'

**Comment by fernandolozano** [comment]
Hi, 
HDIV does not support upload screens in different technologies.
You have to configure it for Spring MVC or for Struts.

This is something we want to improve but it not possible in the current version.

**Comment by gillarramendi** [comment]
Hi,
a lot of time have passed but any updates on this problem?
